version: '3.7'

services:    
    qamq:
        image: recruitai/qamq
        build:
            dockerfile: Dockerfile
            context: microservice/qa
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/picture/app:/workspace/app 
            - ./home/jupyter/.cache:/root/.cache            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5 
            PARALLEL_PROCESS: 1 
        extra_hosts:
            - "rabbitmq:116.202.234.182"
            - "redis:116.202.234.182"
            - "memcached:116.202.234.182"