version: '3.7'

services:    
    
    resumemq:
        image: recruitai/resumemq
        build:
            dockerfile: Dockerfile
            context: microservice/resume
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/resume/app:/workspace/app       
            - ./home/jupyter/.cache:/root/.cache      
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5&heartbeat=3600
            RESUME_PARALLEL_PROCESS: 2
        extra_hosts:
            - "rabbitmq:116.202.234.182"
            - "redis:116.202.234.182"
            - "memcached:116.202.234.182"

