version: '3.7'

services:

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        ports:
            # The standard AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        networks:
            - ai

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        container_name: elasticsearch
        volumes:
            - type: bind
              source: ./config/elasticsearch/config/elasticsearch.yml
              target: /usr/share/elasticsearch/config/elasticsearch.yml
              read_only: true
            - type: volume
              source: elasticsearch
              target: /usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            ES_JAVA_OPTS: "-Xmx512m -Xms512m"
            # ELASTIC_PASSWORD: 
            # Use single node discovery in order to disable production mode and avoid bootstrap checks
            # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
            discovery.type: single-node
        networks:
            - ai
        
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.0
        environment:
            SERVER_NAME: kibana.local
            ELASTICSEARCH_URL: http://elasticsearch:9200
        volumes:
            - type: bind
              source: ./config/kibana/config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - ai

    # logstash:
    #     image: docker.elastic.co/logstash/logstash:7.6.0
    #     volumes:
    #         - type: bind
    #           source: ./config/logstash/config/logstash.yml
    #           target: /usr/share/logstash/config/logstash.yml
    #           read_only: true
    #         - type: bind
    #           source: ./config/logstash/pipeline
    #           target: /usr/share/logstash/pipeline
    #           read_only: true
    #     ports:
    #     - "5000:5000/tcp"
    #     - "5000:5000/udp"
    #     - "9600:9600"
    #     environment:
    #         LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    #     depends_on:
    #         - elasticsearch
    #     networks:
    #         - ai

    # filebeat:
    #     image: "docker.elastic.co/beats/filebeat:7.6.0"
    #     user:
    #         root
    #     volumes:
    #         - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    #         - /var/lib/docker:/var/lib/docker:ro
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         - /var/log/recruitai:/var/log/recruitai:ro
    #     command: ["--strict.perms=false"]
    #     depends_on:
    #         - logstash
    #     networks:
    #         - ai
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"] # https://redis.io/topics/persistence
        volumes:
            - redis-data:/data
        expose:
            - 6379
        networks:
            - ai
    
    rq-dashboard:
        image: eoranged/rq-dashboard
        environment: 
            - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
        ports:
            - 9181:9181
        networks:
            - ai   
    
    label-studio-ner:
        build: label-studio/ner
        ports:
            - 8000:8200 
        volumes:
            - ./label-studio/ner/project:/label-studio/ner
        networks:
            - ai   

    api:
        build: microservice/api
        ports:
            - "8086:5001"
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs 
            - ./microservice/api/app:/workspace/app
        environment:
            - IS_DEV=False
            - RABBIT_DB=amqp://guest:guest@rabbitmq:5672/%2F?connection_attempts=3&heartbeat=3600
            - BATCH_PROCESSING_DELAY=60
        depends_on:
            - elasticsearch
            - redis
        networks:
            - ai

    resumemq:
        build: microservice/resume
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/resume/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            CV_BUCKET_URL: 'staticrecruitai.excellencetechnologies.in'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
            RESUME_PARALLEL_PROCESS: 1
        # mode: replicated
        # replicas: 2
        networks:
            - ai
        
    classifymq:
        build: microservice/classify
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/classify/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
        networks:
            - ai

    skillmq:
        build: microservice/skill
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/skill/app:/workspace/app            
        # Environment variables:
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            
        networks:
            - ai
    
    searchmq:
        build: microservice/search
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/search/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            ELASTIC_SEARCH_URL: 'elasticsearch:9200'
            RESUME_INDEX_NAME: 'resume'
        networks:
            - ai

    skillextractmq:
        build: microservice/skillextract
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/skillextract/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
        networks:
            - ai
    
    gendermq:
        build: microservice/gender
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/gender/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
        networks:
            - ai

    imagemq:
        build: microservice/image
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/image/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
        networks:
            - ai

    datasyncmq:
        build: microservice/datasync
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/datasync/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
            CRON_SCHEDULE: '0 0 * * *'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
        networks:
            - ai

    candidatemq:
        build: microservice/candidate
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/candidate/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
        networks:
            - ai

    filtermq:
        build: microservice/filter
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/filter/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
        networks:
            - ai
      
    statsmq:
        build: microservice/stats
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/stats/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
        networks:
            - ai
    
    picturemq:
        build: microservice/picture
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./batchprocessing:/workspace/batchprocessing 
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/picture/app:/workspace/app            
        environment:
            RABBIT_DB: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            REDIS_HOST: 'redis'
            REDIS_PORT : '6379'
            RECRUIT_BACKEND_DB: "mongodb://176.9.137.77:27017/hr_recruit_dev"
            RECRUIT_BACKEND_DATABASE: "hr_recruit_dev"
        networks:
            - ai

volumes: 
    elasticsearch:
    redis-data:

networks:
    ai:
        driver: bridge