version: '3.7'

services:
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"] # https://redis.io/topics/persistence
        volumes:
            - redis-data:/data
        expose:
            - 6379
        networks:
            - ai
     

    resumemq:
        image: recruitai/resumemq:latest
        build: microservice/resume
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/resume/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5&heartbeat=3600
            RESUME_PARALLEL_PROCESS: 1
        depends_on:
            - redis
        # mode: replicated
        # replicas: 2
        networks:
            - ai
        
    classifymq:
        image: recruitai/classifymq:latest
        build: microservice/classify
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/classify/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5&heartbeat=3600
        networks:
            - ai

    skillmq:
        image: recruitai/skillmq:latest
        build: microservice/skill
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/skill/app:/workspace/app            
        # Environment variables:
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5&heartbeat=3600
            
        networks:
            - ai
    
    searchmq:
        image: recruitai/searchmq:latest
        build: microservice/search
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/search/app:/workspace/app            
        environment:
            - RABBIT_DB=amqp://rabbitmq?connection_attempts=5&retry_delay=5&heartbeat=3600
            - ELASTIC_USERNAME=elastic
            - ELASTIC_PASSWORD=DkIedPPSCb
        networks:
            - ai

    searchindexmq:
        image: recruitai/searchindex:latest
        build: microservice/searchindex
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/searchindex/app:/workspace/app            
        environment:
            - RABBIT_DB=amqp://rabbitmq?connection_attempts=5&retry_delay=5&heartbeat=3600
            - ELASTIC_USERNAME=elastic
            - ELASTIC_PASSWORD=DkIedPPSCb
        networks:
            - ai

    skillextractmq:
        image: recruitai/skillextractmq:latest
        build: microservice/skillextract
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/skillextract/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
        networks:
            - ai
    
    gendermq:
        image: recruitai/gendermq:latest
        build: microservice/gender
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/gender/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
        networks:
            - ai

    imagemq:
        image: recruitai/imagemq:latest
        build: microservice/image
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/image/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
        networks:
            - ai

    datasyncmq:
        image: recruitai/datasyncmq:latest
        build: microservice/datasync
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/datasync/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
            CRON_SCHEDULE: '0 0 * * *'
        networks:
            - ai

    candidatemq:
        image: recruitai/candidatemq:latest
        build: microservice/candidate
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/candidate/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
        networks:
            - ai

    filtermq:
        image: recruitai/filtermq:latest
        build: microservice/filter
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/filter/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
        networks:
            - ai
      
    statsmq:
        image: recruitai/statsmq:latest
        build: microservice/stats
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/stats/app:/workspace/app        
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            RABBIT_DB: 'amqp://127.0.0.1:5672'
            RABBIT_API_URL: 'http://127.0.0.1:15672'
            RABBIT_LOGIN: 'guest:guest'
        network_mode: host
    
    picturemq:
        image: recruitai/picturemq:latest
        build: microservice/picture
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/picture/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
        networks:
            - ai

    summarymq:
        image: recruitai/summarymq:latest
        build: microservice/summary
        volumes:
            - ./pretrained:/workspace/pretrained:ro
            - ./cvreconstruction:/workspace/cvreconstruction 
            - /var/log/recruitai:/workspace/logs  
            - ./microservice/summary/app:/workspace/app            
        environment:
            RABBIT_DB: amqp://rabbitmq?connection_attempts=5&retry_delay=5
        networks:
            - ai
volumes: 
    elasticsearch:
    redis-data:
    certs:

networks:
    ai: